#! /usr/bin/bash

awk '{
start = index($0, "\042")
rest = substr($0, start +1)
end = index(rest, "\042")
qm = substr($0, start +1, end-1)
qmupdt = substr($0, start +1, end-1)
gsub("&","",qmupdt)
gsub(",","",qmupdt)
gsub("\*","",$0)
gsub(qm,qmupdt,$0)
gsub("\"","",$0)
gsub(" ","",$0)
gsub("/","",$0)
gsub(",,",",Z,",$1)
gsub("Jan","01",$1) 
gsub("Feb","02",$1)
gsub("Mar","03",$1)
gsub("Apr","04",$1)
gsub("May","05",$1)
gsub("Jun","06",$1)
gsub("Jul","07",$1)
gsub("Aug","08",$1)
gsub("Sep","09",$1)
gsub("Oct","10",$1)
gsub("Nov","11",$1)
gsub("Dec","12",$1)}NR>1' $1 > $2
#gsub("Dec","12",$1)}NR>1 { printf "%s\\n",$0 }' $1 > $2
